apiVersion: v1
kind: Pod
metadata:
  name: sched-smoke
  namespace: reloc-stage0
spec:
  restartPolicy: Never
  tolerations:
  - operator: Exists
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
    imagePullPolicy: IfNotPresent
